version: 2

sources:
  - name: raw
    schema: DBT_gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: row sales data info
        columns:
          - name: date_date
            description: date of the sale
            tests:
              - not_null
          - name: orders_id
            description: orders id ler
            tests:
              - unique
              - not_null
          - name: pdt_id
            description: id of the product
            tests:
              - not_null
              - unique
                
              
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            tests:
              - not_null
              - unique
            
      - name: ship
        identifier: raw_gz_ship
