version: 2

sources:
  - name: raw
    schema: DBT_gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: row sales data info
              
      - name: product
        identifier: raw_gz_product
            
      - name: ship
        identifier: raw_gz_ship
